### ISSUE TITLE
Install failed test only

### ISSUE THREAD

**Issue by OddSobriquet** [City-Zouitel/JetNote#105]
For a good time, now, I get install_failed_test_only when trying to update the app

Currently installed: 1.9.0
Via Droid-ify(0.5.6) from izzydroid

Android 10 QP1A.190711.020
MIUI 12.0.14 stable

![IMG_20230401_235434.jpg](https://user-images.githubusercontent.com/72888738/229315822-ef26a964-6d77-4d47-8ce3-31c62e28304a.jpg)

**Comment by youndon** [comment]
Hi, "OddSobriquet" I've been seeing your comment since you release it, but I won't be able to respond until I fix this issue and I hope I did.
It was because of the highest version of some dependency in `build.grable` file, And this issue exist in the last previous three releases, And I didn't notice because I run the application directly from my android studio.
Ok I think that's all, let me know if there's something else, And thank you for your comment.
